#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gridChallenge' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING_ARRAY grid as parameter.
#

def gridChallenge(grid):
    # Write your code here
    print('start')
    alphabeticalFlag=True
    for index,item in enumerate(grid):
        if item != ''.join(sorted(item)):
            grid[index]=''.join(sorted(item))
    for index in range(len(grid[0])):
        print(len(grid))
        column = []
        print('Index: ', index)
        for item in grid:
            print('Item: ',item)
            column.append(item[index])
        if ''.join(column) != ''.join(sorted(column)):
            alphabeticalFlag=False
            
            break
    if alphabeticalFlag:
        return 'YES'
    else:
        return 'NO'
        
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        grid = []

        for _ in range(n):
            grid_item = input()
            grid.append(grid_item)

        result = gridChallenge(grid)

        fptr.write(result + '\n')

    fptr.close()
