#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def countingSort(arr):
    # Write your code here
    unique_list=[]
    maxValue=max(arr)
    minValue=min(arr)
    output_arr=[0]*(100)
    #print(maxValue,minValue,output_arr)
    for item in arr:
        if item not in unique_list:
            unique_list.append(item)
    dictionary={}
    for unique_item in unique_list:
        #initialise count = 0
        dictionary.update({unique_item:0})
    for unique_item in unique_list:
        for item in arr:
            if unique_item==item:
                dictionary[unique_item]+=1
    #print(dictionary)
    for indexnumber in range(100):
        for key, dict_value in dictionary.items():
            #print("key = ",key)
            #print(type(key))
            #print(type(output_arr[item+1]))
            if key==indexnumber:
                #print("HELLO")
                #print(key)
                #print(output_arr[indexnumber-1])
                output_arr[indexnumber] = dict_value
    #print(output_arr)
    return output_arr

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
