#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    # Write your code here
    number=0
    for index, num in enumerate(str(k)):
        number+=int(num)
    number=number*n
    while len(str(number))>1:
        number=sDigit(number)
    return number
    
def sDigit(k):
    number=0
    for index, num in enumerate(str(k)):
        number+=int(num)
    return number
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()
